#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

PYTHON=/usr/bin/python3
CONFIG=/etc/querierd
PIDFILE=/var/run/querierd.pid

start_service() {
	procd_open_instance
	procd_set_param command $PYTHON -m querier.daemon start
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	$PYTHON -m querier.daemon stop
}

restart_service() {
	$PYTHON -m querier.daemon restart
}
